-- Change leader key to ,
vim.g.mapleader = ","

require "user.rustaceanvim" -- This needs to be first because of the way the plugin works
require "user.plugins"
require "user.options"
require "user.keymaps"
require "user.treesitter"
require "user.toggleterm"
require "user.bufferline"
require "user.lualine"
require "user.luasnip"
require "user.nvim_cmp"
require "user.nvim_tree"
require "user.gitsigns"
require "user.lsp"
require "user.telescope"
require "user.lsp_signature"
require "user.nvim_surround"
require "user.globals"
require "user.eyeliner"
